### PR TITLE
Multi feature selection and centreline hiding

### PR DESCRIPTION
**Pull request by napakalas**
- Previously, for a node with multiple features, the feature at index 0 was selected. Now, the selected feature is the one closest to its neighbors.
- The centerline and the nodes within it are hidden by default. Centerline segments will be exposed only when at least one path passes through them.

### CODE REVIEW

**Comment by dbrnz** [comment]
@napakalas I'm I bit confused by this PR and the force-push referred to above...

**Comment by napakalas** [comment]
I found that this PR has not been approved and has 5 commits ahead and 4 commits behind. Since I need to sync with the current mapmaker, I created a new branch in my repo and then synchronized my main branch, which resulted in the deletion of my commits. I didn’t realize that this action would cause a force push.

My plan is to create a new PR for my proposed update. Do you have any suggestions for this?

**Comment by dbrnz** [comment]
All good -- it appears the force push was in your fork, against your `main`.

Simply create a new PR for your proposed update.

BTW are you aware that you can update an open PR by simply pushing to your repo's branch used to create the PR? It's also good practise to have separate local branches for each PR.

**Comment by napakalas** [comment]
Thanks for the suggestion; I'll do as you suggested.

**Comment by dbrnz** [comment]
Yes, the general idea is that your fork's `main` should always mirror `upstream/main` and only ever by updated by fetch/merge/pull from upstream. Then maybe have a private `devel` branch which is your version of things (and will have `main` merged into it from time to time) and branches off `devel` for what will become PR's.

**Pull request closed without merging**
